const $=id=>document.getElementById(id);
const BUILD='2026-08-18 v6';
const canvas=$('stage'),ctx=canvas.getContext('2d',{willReadFrequently:true});
let original=null,current=null,history=[],abort=false,model=null,sequenceFrames=[],compareMode=false,loadedProfile=null,busy=false,dreamNodes=[],useGraphFeatures=false;
const controls=['strength','steps','octaves','zoom','detail','color','tile','layerDepth','layerSpread','noise'];
for(const id of controls){const el=$(id),out=$(id+'Out');if(!el||!out)continue;const sync=()=>out.textContent=el.value;el.addEventListener('input',sync);sync()}
const presets={classic:{strength:.85,steps:24,octaves:4,zoom:1.025,detail:.72,color:.08,tile:192,layerDepth:.55,layerSpread:2,noise:.08},eyes:{strength:1.15,steps:30,octaves:4,zoom:1.032,detail:.9,color:.12,tile:160,layerDepth:.7,layerSpread:3,noise:.14},fur:{strength:1.0,steps:26,octaves:4,zoom:1.02,detail:.98,color:.05,tile:160,layerDepth:.4,layerSpread:2,noise:.1},architecture:{strength:1.0,steps:26,octaves:4,zoom:1.018,detail:.55,color:.04,tile:224,layerDepth:.62,layerSpread:2,noise:.05},acid:{strength:1.35,steps:34,octaves:5,zoom:1.045,detail:.84,color:.24,tile:160,layerDepth:.78,layerSpread:3,noise:.2},mild:{strength:.45,steps:12,octaves:3,zoom:1.012,detail:.4,color:.02,tile:224,layerDepth:.5,layerSpread:1,noise:.03}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=presets[b.dataset.preset];for(const[k,v]of Object.entries(p)){const e=$(k);if(e){e.value=v;e.dispatchEvent(new Event('input'))}}});
function status(s){$('status').textContent=`${s} ｜ ${BUILD}`}
function cloneImageData(x){return new ImageData(new Uint8ClampedArray(x.data),x.width,x.height)}
function drawData(data){canvas.width=data.width;canvas.height=data.height;ctx.putImageData(data,0,0);current=cloneImageData(data);$('drop').classList.add('hidden')}
function pushHistory(){if(current){history.push(cloneImageData(current));if(history.length>12)history.shift()}}
function withTimeout(p,ms,label){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error(label)),ms))])}
function profileConfig(){const p=$('modelProfile').value;return p==='light'?{version:1,alpha:.25,name:'軽量 MobileNetV1 0.25'}:p==='balanced'?{version:1,alpha:.5,name:'標準 MobileNetV1 0.50'}:{version:2,alpha:.5,name:'高品質 MobileNetV2 0.50'}}
function disposeModel(){try{model?.model?.dispose()}catch{}model=null;loadedProfile=null;dreamNodes=[];useGraphFeatures=false}
$('modelProfile').addEventListener('change',()=>{disposeModel();status('モデル変更。次回Dream時に読み込みます')});
function graphNodeNames(){const g=model?.model?.executor?.graph;let names=[];if(g?.nodes){if(Array.isArray(g.nodes))names=g.nodes.map(n=>n?.name).filter(Boolean);else names=Object.keys(g.nodes)}if(!names.length&&g?.nodeMap){if(g.nodeMap instanceof Map)names=[...g.nodeMap.keys()];else names=Object.keys(g.nodeMap)}return names}
function discoverDreamNodes(){const names=graphNodeNames();const filtered=names.filter(n=>/(Mobilenet|mobilenet|expanded_conv|Conv2d|depthwise|pointwise)/.test(n)&&/(Relu|relu|Relu6|Conv2d|depthwise|pointwise)/.test(n)&&!/(weights|kernel|bias|read|Assign|Const)/i.test(n));if(!filtered.length)return[];const depth=Math.max(0,Math.min(1,+$('layerDepth').value||.55));const spread=Math.max(1,Math.min(3,+$('layerSpread').value||2));const center=Math.round((filtered.length-1)*depth);const offsets=spread===1?[0]:spread===2?[-.12,.12]:[-.18,0,.18];const chosen=[];for(const o of offsets){const i=Math.max(0,Math.min(filtered.length-1,Math.round(center+o*filtered.length)));if(!chosen.includes(filtered[i]))chosen.push(filtered[i])}return chosen}
async function verifyDreamNodes(nodes){if(!nodes.length)return false;const z=tf.zeros([1,224,224,3]);try{const out=model.model.execute(z,nodes);const arr=Array.isArray(out)?out:[out];for(const t of arr){await t.data();t.dispose()}return true}catch(e){console.warn('Intermediate nodes unavailable, fallback to embedding',e);return false}finally{z.dispose()}}
async function ensureModel(){const key=$('modelProfile').value;if(model&&loadedProfile===key)return;disposeModel();const cfg=profileConfig();if(typeof tf==='undefined')throw new Error('TensorFlow.js本体が読み込めていません');if(typeof mobilenet==='undefined')throw new Error('MobileNetライブラリが読み込めていません');status(`TensorFlow初期化中 (${cfg.name})`);await withTimeout(tf.ready(),12000,'TensorFlow初期化が12秒を超えました');if(tf.getBackend()!=='webgl'){try{await withTimeout(tf.setBackend('webgl'),8000,'WebGL初期化失敗');await tf.ready()}catch(e){console.warn(e);await withTimeout(tf.setBackend('cpu'),5000,'CPUバックエンド初期化失敗');await tf.ready()}}status(`モデル取得中 (${cfg.name})`);model=await withTimeout(mobilenet.load({version:cfg.version,alpha:cfg.alpha}),30000,'MobileNet取得が30秒を超えました');status('夢を見る層を探しています…');dreamNodes=discoverDreamNodes();useGraphFeatures=await verifyDreamNodes(dreamNodes);if(!useGraphFeatures){const probe=tf.zeros([64,64,3]);try{const emb=model.infer(probe,true);await emb.data();emb.dispose()}finally{probe.dispose()}}loadedProfile=key;status(useGraphFeatures?`準備完了 / 中間層 ${dreamNodes.length}枚 / ${tf.getBackend()}`:`準備完了 / 埋め込みfallback / ${tf.getBackend()}`)}
function imageDataToTensor(data){return tf.tidy(()=>tf.browser.fromPixels(data).toFloat())}
function tensorToImageData(t){return tf.tidy(()=>t.clipByValue(0,255).cast('int32'))}
async function tensorToData(t){const[h,w]=t.shape,vals=await t.data(),out=new Uint8ClampedArray(w*h*4);for(let i=0,j=0;i<vals.length;i+=3,j+=4){out[j]=vals[i];out[j+1]=vals[i+1];out[j+2]=vals[i+2];out[j+3]=255}return new ImageData(out,w,h)}
function roll2d(t,sy,sx){return tf.tidy(()=>{const[h,w]=t.shape,y=((sy%h)+h)%h,x=((sx%w)+w)%w;let r=t;if(y)r=tf.concat([r.slice([h-y,0,0],[y,w,3]),r.slice([0,0,0],[h-y,w,3])],0);if(x)r=tf.concat([r.slice([0,w-x,0],[h,x,3]),r.slice([0,0,0],[h,w-x,3])],1);return r})}
function refreshDreamNodes(){if(!model||!useGraphFeatures)return;const next=discoverDreamNodes();if(next.length)dreamNodes=next}
function dreamLoss(x){if(useGraphFeatures&&dreamNodes.length){const batched=tf.image.resizeBilinear(x,[224,224],true).div(255).expandDims(0);const out=model.model.execute(batched,dreamNodes),arr=Array.isArray(out)?out:[out];let loss=tf.scalar(0);for(const o of arr){const rms=o.square().mean().sqrt().add(1e-6);loss=loss.add(o.square().mean().div(rms))}return loss.div(Math.max(1,arr.length))}const emb=model.infer(x,true);return emb.square().mean()}
function seededNoise(shape,amount,seed){if(amount<=0)return tf.zeros(shape);let h=2166136261;for(let i=0;i<seed.length;i++){h^=seed.charCodeAt(i);h=Math.imul(h,16777619)}return tf.randomNormal(shape,0,amount,'float32',Math.abs(h%2147483647))}
async function dreamStep(img,stepSize,detail,noiseAmount,seed){const jitter=Math.max(4,Math.min(28,Math.round((+$('tile').value||192)/10))),sx=Math.floor((Math.random()-.5)*jitter),sy=Math.floor((Math.random()-.5)*jitter),rolled=roll2d(img,sy,sx);const grad=tf.tidy(()=>{let g=tf.grad(x=>dreamLoss(x))(rolled);if(detail>.05){const blur=tf.avgPool(g.expandDims(0),3,1,'same').squeeze([0]);g=g.mul(1-detail*.4).add(g.sub(blur).mul(detail*.75))}return g.div(g.square().mean().sqrt().add(1e-8))});let next=tf.tidy(()=>rolled.add(grad.mul(stepSize)).clipByValue(0,255));grad.dispose();rolled.dispose();if(noiseAmount>0){const n=seededNoise(next.shape,noiseAmount,seed);const nn=tf.tidy(()=>next.add(n).clipByValue(0,255));next.dispose();n.dispose();next=nn}const restored=roll2d(next,-sy,-sx);next.dispose();return restored}
function tameColor(t,a){return tf.tidy(()=>{const mean=t.mean(2,true),sat=Math.max(.65,Math.min(1.25,.88+a*.55));return mean.add(t.sub(mean).mul(sat)).clipByValue(0,255)})}
function localContrast(t,amount){if(amount<=0)return t.clone();return tf.tidy(()=>{const blur=tf.avgPool(t.expandDims(0),5,1,'same').squeeze([0]);return t.add(t.sub(blur).mul(amount*.08)).clipByValue(0,255)})}
function zoomTensor(t,z){if(z<=1.0001)return t.clone();return tf.tidy(()=>{const[h,w]=t.shape,nh=Math.max(2,Math.floor(h/z)),nw=Math.max(2,Math.floor(w/z)),y=Math.floor((h-nh)/2),x=Math.floor((w-nw)/2);return tf.image.resizeBilinear(t.slice([y,x,0],[nh,nw,3]),[h,w],true)})}
async function runDream({record=false}={}){if(!current)return status('先に画像を選んでください');if(busy)return status('処理中です');busy=true;$('run').disabled=true;abort=false;let base=null,x=null;try{await ensureModel();refreshDreamNodes();pushHistory();base=imageDataToTensor(current);const target=+$('size').value,ratio=Math.min(1,target/Math.max(base.shape[0],base.shape[1]));if(ratio<1){const r=tf.image.resizeBilinear(base,[Math.round(base.shape[0]*ratio),Math.round(base.shape[1]*ratio)],true);base.dispose();base=r}const steps=+$('steps').value,oct=+$('octaves').value,str=+$('strength').value,detail=+$('detail').value,color=+$('color').value,zoom=+$('zoom').value,noise=+$('noise').value||0,seed=($('seed')?.value||'subeha');x=base.clone();for(let o=0;o<oct;o++){if(abort)break;const scale=Math.pow(1.28,o-(oct-1)),nh=Math.max(96,Math.round(base.shape[0]*scale)),nw=Math.max(96,Math.round(base.shape[1]*scale));if(x.shape[0]!==nh||x.shape[1]!==nw){const r=tf.image.resizeBilinear(x,[nh,nw],true);x.dispose();x=r}for(let s=0;s<steps;s++){if(abort)break;const nx=await dreamStep(x,(useGraphFeatures?.48:.68)*str,detail,noise,`${seed}-${o}-${s}`);x.dispose();x=nx;if((s+1)%3===0){const c=tameColor(x,color);x.dispose();x=c;const lc=localContrast(x,detail);x.dispose();x=lc;await tf.nextFrame()}status(`夢見中 ${o+1}/${oct} ・ ${s+1}/${steps}${useGraphFeatures?' ・ 中間層':' ・ fallback'}`)}}if($('autoZoom').checked||record){const z=zoomTensor(x,zoom);x.dispose();x=z}const rgb=tensorToImageData(x),data=await tensorToData(rgb);rgb.dispose();drawData(data);status(abort?'停止しました':'完了');return data}catch(e){console.error(e);if(useGraphFeatures){useGraphFeatures=false;status(`中間層で失敗。fallbackへ切替: ${e.message}`)}else status(`エラー: ${e.message}`)}finally{try{x?.dispose()}catch{}try{base?.dispose()}catch{}busy=false;$('run').disabled=false}}
$('run').onclick=()=>runDream();$('stop').onclick=()=>{abort=true;status('停止要求')};$('undo').onclick=()=>{const x=history.pop();if(x)drawData(x)};$('reset').onclick=()=>{if(original){pushHistory();drawData(original)}};$('download').onclick=()=>downloadCanvas('deepdream.png');$('fit').onclick=()=>canvas.scrollIntoView({behavior:'smooth',block:'center'});$('split').onclick=()=>{compareMode=!compareMode;renderCompare()};$('compare').oninput=renderCompare;$('random').onclick=()=>{for(const id of['strength','steps','octaves','zoom','detail','color','layerDepth','noise']){const e=$(id);if(!e)continue;const min=+e.min,max=+e.max,step=+e.step||.01,v=Math.round((min+Math.random()*(max-min))/step)*step;e.value=v;e.dispatchEvent(new Event('input'))}};
function renderCompare(){if(!compareMode||!original||!current)return current&&ctx.putImageData(current,0,0);const p=+$('compare').value;ctx.putImageData(current,0,0);const tmp=document.createElement('canvas');tmp.width=original.width;tmp.height=original.height;tmp.getContext('2d').putImageData(original,0,0);ctx.save();ctx.beginPath();ctx.rect(0,0,canvas.width*p,canvas.height);ctx.clip();ctx.drawImage(tmp,0,0,canvas.width,canvas.height);ctx.restore();ctx.strokeStyle='white';ctx.beginPath();ctx.moveTo(canvas.width*p,0);ctx.lineTo(canvas.width*p,canvas.height);ctx.stroke()}
async function loadFile(file){try{const bmp=await createImageBitmap(file),max=1400,r=Math.min(1,max/Math.max(bmp.width,bmp.height));canvas.width=Math.round(bmp.width*r);canvas.height=Math.round(bmp.height*r);ctx.drawImage(bmp,0,0,canvas.width,canvas.height);original=ctx.getImageData(0,0,canvas.width,canvas.height);current=cloneImageData(original);history=[];$('drop').classList.add('hidden');status(`${canvas.width}×${canvas.height} 読み込み完了`);bmp.close()}catch(e){status(`画像読込失敗: ${e.message}`)}}
$('file').onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);['dragenter','dragover'].forEach(ev=>document.addEventListener(ev,e=>e.preventDefault()));document.addEventListener('drop',e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f&&f.type.startsWith('image/'))loadFile(f)});
function downloadCanvas(name){const a=document.createElement('a');a.download=name;a.href=canvas.toDataURL('image/png');a.click()}
$('sequence').onclick=async()=>{if(!current||busy)return;sequenceFrames=[];const n=Math.min(24,Math.max(2,+$('frames').value));for(let i=0;i<n;i++){if(abort)break;await runDream({record:true});sequenceFrames.push(canvas.toDataURL('image/png'));status(`連続夢 ${i+1}/${n}`)}$('exportZip').disabled=sequenceFrames.length===0;status(`連続夢 完了 ${sequenceFrames.length}枚`)};
$('exportZip').onclick=()=>sequenceFrames.forEach((url,i)=>setTimeout(()=>{const a=document.createElement('a');a.href=url;a.download=`deepdream-${String(i+1).padStart(3,'0')}.png`;a.click()},i*220));
let hold;canvas.addEventListener('pointerdown',()=>{hold=setTimeout(()=>{compareMode=!compareMode;renderCompare()},650)});canvas.addEventListener('pointerup',()=>clearTimeout(hold));status('画像を選んでください');