import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {VRMLoaderPlugin,VRMUtils} from '@pixiv/three-vrm';
const $=id=>document.getElementById(id),c=$('c'),stage=$('stage'),vf=$('vrmFile'),af=$('audioFile'),bf=$('bgFile'),play=$('play'),stop=$('stop'),portrait=$('portrait'),full=$('fullbody'),flip=$('flip'),reset=$('reset'),zoom=$('zoom'),seek=$('seek'),status=$('status'),meter=$('meterBar'),hint=$('dropHint'),clearBg=$('clearBg');
const r=new THREE.WebGLRenderer({canvas:c,antialias:true,alpha:true,preserveDrawingBuffer:true});r.outputColorSpace=THREE.SRGBColorSpace;r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=1.1;r.setClearColor(0x17171c,1);const s=new THREE.Scene(),cam=new THREE.PerspectiveCamera(24,1,.1,100);s.add(new THREE.HemisphereLight(0xffffff,0x202027,2.4));const k=new THREE.DirectionalLight(0xffffff,3.6);k.position.set(2.4,4,4);s.add(k);const f=new THREE.DirectionalLight(0xcbd5ff,1.2);f.position.set(-2.5,1.7,3);s.add(f);
let vrm,audio,aurl,burl,ctx,src,an,freq,time,smooth=0,h=1.7,mode='portrait',dir=0,yaw=0,pitch=0,drag=false,lx=0,ly=0,b={};
function resize(){const q=stage.getBoundingClientRect();r.setPixelRatio(Math.min(devicePixelRatio||1,2));r.setSize(q.width,q.height,false);cam.aspect=q.width/q.height;cam.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);resize();
const bone=n=>vrm?.humanoid?.getNormalizedBoneNode(n)||null;
function cache(){b={head:bone('head'),neck:bone('neck'),chest:bone('chest'),spine:bone('spine'),lua:bone('leftUpperArm'),rua:bone('rightUpperArm'),lla:bone('leftLowerArm'),rla:bone('rightLowerArm'),lh:bone('leftHand'),rh:bone('rightHand')}}
function frame(m=mode){if(!vrm)return;mode=m;const z=Number(zoom.value)/100;if(m==='full'){cam.position.set(0,h*.54,h*1.82*z);cam.lookAt(0,h*.53,0)}else{cam.position.set(0,h*.70,h*1.12*z);cam.lookAt(0,h*.72,0)}cam.updateProjectionMatrix()}
function pose(t=0,e=0){const q=Math.sin(t*.9)*.012;if(b.lua)b.lua.rotation.set(.08,0,-1.18+q);if(b.rua)b.rua.rotation.set(.08,0,1.18-q);if(b.lla)b.lla.rotation.set(.14,0,-.12);if(b.rla)b.rla.rotation.set(.14,0,.12);if(b.lh)b.lh.rotation.set(0,0,-.04);if(b.rh)b.rh.rotation.set(0,0,.04);if(b.spine)b.spine.rotation.x=.018+q*.3;if(b.chest){b.chest.rotation.y=Math.sin(t*.34)*.018;b.chest.rotation.x=.012+e*.015+q}if(b.neck)b.neck.rotation.z=Math.sin(t*.43)*.014;if(b.head){b.head.rotation.y=yaw+Math.sin(t*.73)*.038;b.head.rotation.x=pitch+Math.sin(t*.51)*.014-e*.02}}
function ready(){play.disabled=!(vrm&&audio);stop.disabled=!audio}
vf.addEventListener('change',async()=>{const file=vf.files?.[0];if(!file)return;status.textContent='VRMを読み込み中…';try{const buf=await file.arrayBuffer(),loader=new GLTFLoader();loader.register(p=>new VRMLoaderPlugin(p));const gltf=await new Promise((ok,no)=>loader.parse(buf,'',ok,no));if(vrm)s.remove(vrm.scene);vrm=gltf.userData.vrm;VRMUtils.removeUnnecessaryVertices(gltf.scene);VRMUtils.combineSkeletons(gltf.scene);dir=0;vrm.scene.rotation.y=0;s.add(vrm.scene);const box=new THREE.Box3().setFromObject(vrm.scene),ct=new THREE.Vector3(),sz=new THREE.Vector3();box.getCenter(ct);box.getSize(sz);vrm.scene.position.x-=ct.x;vrm.scene.position.z-=ct.z;const g=new THREE.Box3().setFromObject(vrm.scene);vrm.scene.position.y-=g.min.y;h=Math.max(sz.y,.1);cache();pose();frame('portrait');hint.style.display='none';status.textContent=`${file.name}：前向きで読み込み完了`;ready()}catch(e){console.error(e);status.textContent='VRM読み込み失敗'}});
af.addEventListener('change',()=>{const file=af.files?.[0];if(!file)return;if(audio){audio.pause();audio.src=''}if(aurl)URL.revokeObjectURL(aurl);aurl=URL.createObjectURL(file);audio=new Audio(aurl);audio.preload='auto';src=an=ctx=null;audio.addEventListener('loadedmetadata',()=>{seek.disabled=false;status.textContent=`音声 ${Math.round(audio.duration)}秒 読み込み完了`;ready()});audio.addEventListener('timeupdate',()=>{if(audio.duration)seek.value=String(Math.round(audio.currentTime/audio.duration*1000))})});
bf.addEventListener('change',()=>{const file=bf.files?.[0];if(!file)return;if(burl)URL.revokeObjectURL(burl);burl=URL.createObjectURL(file);new THREE.TextureLoader().load(burl,t=>{t.colorSpace=THREE.SRGBColorSpace;s.background=t;status.textContent='背景読み込み完了'})});clearBg.addEventListener('click',()=>{s.background=null;r.setClearColor(0x17171c,1)});
async function wire(){if(!audio||src)return;ctx=new (window.AudioContext||window.webkitAudioContext)();src=ctx.createMediaElementSource(audio);an=ctx.createAnalyser();an.fftSize=1024;an.smoothingTimeConstant=.5;freq=new Uint8Array(an.frequencyBinCount);time=new Uint8Array(an.fftSize);src.connect(an);an.connect(ctx.destination)}
play.addEventListener('click',async()=>{if(!vrm||!audio)return;await wire();if(ctx.state==='suspended')await ctx.resume();if(audio.paused){await audio.play();play.textContent='一時停止'}else{audio.pause();play.textContent='再生'}});stop.addEventListener('click',()=>{if(!audio)return;audio.pause();audio.currentTime=0;play.textContent='再生'});seek.addEventListener('input',()=>{if(audio?.duration)audio.currentTime=Number(seek.value)/1000*audio.duration});portrait.addEventListener('click',()=>frame('portrait'));full.addEventListener('click',()=>frame('full'));zoom.addEventListener('input',()=>frame(mode));flip.addEventListener('click',()=>{if(!vrm)return;dir=dir===0?Math.PI:0;vrm.scene.rotation.y=dir;status.textContent=dir===0?'正面：標準':'正面：180°反転'});reset.addEventListener('click',()=>{yaw=pitch=0;dir=0;if(vrm)vrm.scene.rotation.y=0;frame('portrait')});
c.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-lx)*.005;pitch=Math.max(-.2,Math.min(.2,pitch+(e.clientY-ly)*.0025));lx=e.clientX;ly=e.clientY});c.addEventListener('pointerup',()=>drag=false);
function env(){if(!an||!audio||audio.paused)return 0;an.getByteTimeDomainData(time);let sum=0;for(const v of time){const x=(v-128)/128;sum+=x*x}const rms=Math.sqrt(sum/time.length);an.getByteFrequencyData(freq);let sp=0,n=0,ny=(ctx?.sampleRate||48000)/2;for(let i=0;i<freq.length;i++){const hz=i/freq.length*ny;if(hz>120&&hz<4200){sp+=freq[i]/255;n++}}const v=Math.min(1,Math.max(0,(rms-.01)*8.3+(n?sp/n*.13:0)));smooth=smooth*.64+v*.36;return smooth}
function loop(ms){requestAnimationFrame(loop);const t=audio?.currentTime??ms/1000,e=env();meter.style.width=`${Math.round(e*100)}%`;if(vrm){pose(t,e);const em=vrm.expressionManager,on=e>.025;em?.setValue('aa',on?Math.min(1,e*.92):0);em?.setValue('ih',on?Math.max(0,Math.sin(t*14))*e*.22:0);em?.setValue('ou',on?Math.max(0,Math.sin(t*10+1.1))*e*.17:0);em?.setValue('ee',on?Math.max(0,Math.sin(t*8+2.2))*e*.09:0);const bp=(ms/1000)%4.5,bl=bp>4.3?Math.sin((bp-4.3)/.2*Math.PI):0;em?.setValue('blink',Math.max(0,bl));em?.update();vrm.update(1/60)}r.render(s,cam)}requestAnimationFrame(loop);
