// Generated by scripts/build-backup-timeline.mjs.
// This placeholder keeps the backup composition buildable before phone timing is imported.

export type TimingPart = {
  text: string;
  startMs: number;
  endMs: number;
  confidence?: number;
};

export type MouthFrame = {
  tMs: number;
  open: number;
  voiced: boolean;
};

export type DisplayCaption = {
  text: string;
  startMs: number;
  endMs: number;
};

export const backupMeta = {
  schema: 'subeha-vtuber-backup-v1',
  source: 'placeholder',
  durationMs: 60000,
} as const;

export const timingParts: TimingPart[] = [];
export const displayCaptions: DisplayCaption[] = [];
export const mouthFrames: MouthFrame[] = [];
