plugins { id 'com.android.application' }
android {
  namespace 'jp.subeha.wordtiming'
  compileSdk 35
  defaultConfig {
    applicationId 'jp.subeha.wordtiming'
    minSdk 34
    targetSdk 35
    versionCode 1
    versionName '0.1.0'
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}
