(()=>{
'use strict';
const A=window.NinjaApp,{META,$,$$,store}=A,root=document.documentElement,body=document.body;
function font(d){A.fontScale=Math.min(1.25,Math.max(.88,A.fontScale+d));root.style.setProperty('--font-scale',A.fontScale.toFixed(2));store.set('ninja-font',A.fontScale)}
$('#fontDown').onclick=()=>font(-.06);$('#fontUp').onclick=()=>font(.06);
$('#motionToggle').onclick=e=>{A.motionOff=!A.motionOff;body.classList.toggle('motion-off',A.motionOff);e.currentTarget.setAttribute('aria-pressed',A.motionOff);e.currentTarget.textContent=A.motionOff?'動':'止';if(A.motionOff)A.reveals.forEach(x=>x.classList.add('is-visible'))};
$('#compactToggle').onclick=e=>{const on=$('#registry').classList.toggle('compact');e.currentTarget.setAttribute('aria-pressed',on);e.currentTarget.textContent=on?'読':'覧'};
let ac=null;
function audio(){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('audio unsupported');return ac||(ac=new C())}
A.tick=()=>{const a=audio(),o=a.createOscillator(),g=a.createGain();o.type='square';o.frequency.value=180+A.current*3;g.gain.setValueAtTime(.018,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.045);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.05)};
$('#soundToggle').onclick=e=>{A.soundOn=!A.soundOn;e.currentTarget.setAttribute('aria-pressed',A.soundOn);e.currentTarget.textContent=A.soundOn?'音':'無';if(A.soundOn)A.tick()};
$('#gong').onclick=()=>{const a=audio(),now=a.currentTime;[82,123,164,246].forEach((f,i)=>{const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.09/(i+1),now+.03);g.gain.exponentialRampToValueAtTime(.0001,now+3.5+i*.4);o.connect(g).connect(a.destination);o.start(now);o.stop(now+4.2)});body.classList.add('phase-final')};
const rc=$('#relationCanvas'),ctx=rc.getContext('2d');
function relation(){const d=Math.min(devicePixelRatio||1,2),r=rc.getBoundingClientRect();if(!r.width)return;rc.width=r.width*d;rc.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height,cx=w*.52,cy=h*.48;ctx.fillStyle='#070706';ctx.fillRect(0,0,w,h);META.forEach((m,i)=>{const a=i/32*Math.PI*2-.5,rad=Math.min(w,h)*(.3+(i%3)*.018),x=cx+Math.cos(a)*rad,y=cy+Math.sin(a)*rad;ctx.strokeStyle=`rgba(236,52,41,${.08+m.confidence*.002})`;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle=i<A.current?'#ec3429':'#5a544a';ctx.beginPath();ctx.arc(x,y,i===A.current-1?6:3.2,0,Math.PI*2);ctx.fill();if(i===A.current-1){ctx.fillStyle='#c4f35b';ctx.font='11px monospace';ctx.fillText(m.name,x+9,y+3)}});ctx.strokeStyle='#c4f35b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,18,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#c4f35b';ctx.font='12px serif';ctx.textAlign='center';ctx.fillText('巣',cx,cy+4);ctx.textAlign='left'}
A.relationDraw=relation;relation();setInterval(relation,700);addEventListener('resize',relation);
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.key==='ArrowDown'&&A.current<32){e.preventDefault();A.jump(Math.max(1,A.current+1))}if(e.key==='ArrowUp'&&A.current>1){e.preventDefault();A.jump(A.current-1)}if(e.key.toLowerCase()==='e')$('#evidence').classList.toggle('is-open')});
})();